source 'http://ruby.taobao.org'

gem 'rails'
gem 'sqlite3'
gem 'hashie'
gem 'therubyracer'
gem "less-rails"
gem "twitter-bootstrap-rails"
gem "thin"

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# Deploy with Capistrano
gem 'capistrano'
gem 'rvm-capistrano'